config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  
  get 'archive', to: 'posts#archive', as: 'archive'
  get 'unpublished', to: 'posts#unpublished', as: 'unpublished'
  get 'feed', to: 'posts#feed', as: 'feed'
  
  resources :posts
  resources :images
  
  get 'rename-finder-items-action', to: 'apps#rename_finder_items_action', as: :rename_finder_items_action
  get 'snippose', to: 'apps#snippose', as: :snippose
  get 'mdx', to: 'apps#mdx', as: :mdx
  
end

app/models/image.rb
class Image < ActiveRecord::Base
  attr_accessor :key
  
  has_one_attached :picture
  
  validate :key_must_be_valid
  
  def key_must_be_valid
    logger.debug Rails.configuration.post_key
    if key != Rails.configuration.post_key
      errors.add(:key, 'invalid key')
    end
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessor :key
  
#  validates :slug, presence: true, uniqueness: true
  validate :key_must_be_valid
  
  def slug_or_id
    slug? ? slug : id
  end
  
  def key_must_be_valid
    if key != Rails.configuration.post_key
      errors.add(:key, 'invalid key')
    end
  end
  
  def posted_at_formatted
    posted_at.strftime('%B %e, %Y')
  end
  
  def teaser
    body.split("\r\n\r\n", 2)[0] # try to return the first paragraph
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def in_the_backdoor?
    request.host_with_port.include? "herokuapp.com"
  end

  helper_method :in_the_backdoor?
end

app/controllers/apps_controller.rb
class AppsController < ApplicationController
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def index
    @images = Image.all
  end
  
  def new
    @image = Image.new
  end
  
  def edit
    @image = Image.find(params[:id])
  end
  
  def create
    @image = Image.new(image_params)

    if @image.save
      redirect_to images_path
    else
      render 'new'
    end
  end

  def update
    @image = Image.find(params[:id])
    
    if image_params[:name].downcase == 'delete' && image_params[:key] == Rails.configuration.post_key
      @image.destroy
      redirect_to images_path
    else
      @image.update(image_params)

      if @image.save
        redirect_to images_path
      else
        render 'edit'
      end
    end
  end
  
  private
  
  def image_params
    params.require(:image).permit(:name, :key, :picture)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update]
  
  def index
    @posts = Post.where(published: true).order(posted_at: :desc).take(5)
  end
  
  def feed
    @posts = Post.where(published: true).order(posted_at: :desc)
    respond_to do |format|
      format.rss { render :layout => false }
    end
  end
  
  def show
  end
  
  def new
    @post = Post.new(posted_at: DateTime.now)
  end
  
  def edit
  end
  
  def create
    @post = Post.new(post_params)
    @post.posted_at = DateTime.now if @post.posted_at.nil?

    if @post.save
      if @post.published
        redirect_to @post
      else
        redirect_to unpublished_path
      end
    else
      render 'new'
    end
  end
  
  def update
    @post.update(post_params)
    
    if post_params[:title].downcase == 'delete' && post_params[:key] == Rails.configuration.post_key
      @post.destroy
      redirect_to posts_path
    else
      if @post.save
          if @post.published
          redirect_to @post
        else
          redirect_to unpublished_path
        end
      else
        render 'edit'
      end
    end
  end
  
  def archive
    @posts = Post.where(published: true).order(posted_at: :desc)
  end
  
  def unpublished
    @posts = Post.where(published: false).order(posted_at: :desc)
    @published_posts = Post.where(published: true).order(posted_at: :desc)
  end
  
  private
  
  def set_post
    @post = Post.find_by(slug: params[:id]) || Post.find(params[:id])
  end
  
  def post_params
    params.require(:post).permit(:title, :posted_at, :published, :key, :body, :slug)
  end
end

app/helpers/application_helper.rb
require 'redcarpet/render_strip'

module ApplicationHelper
  def markdown(content)
    @markdown ||= Redcarpet::Markdown.new(ImageReplacer, autolink: true, space_after_headers: true, fenced_code_blocks: true, tables: true)
    @markdown.render(content).html_safe
  end
  
  def plaintext(content)
    @plaintext ||= Redcarpet::Markdown.new(Redcarpet::Render::StripDown)
    @plaintext.render(content)
  end
end

class ImageReplacer < Redcarpet::Render::HTML
  include Sprockets::Rails::Helper
  
  def image(link, alt_text, title)
    image = Image.find_by_name(link)
    if image && image.picture.attached?
      image_tag make_url(image.picture), alt: alt_text, title: title, class: "img-responsive"
    else
      image_tag link, alt: alt_text, title: title, class: "img-responsive"
    end

    image_tag image ? make_url(image.picture) : link, alt: alt_text, title: title, class: "img-responsive"
  end

  private

  def make_url(attachment)
    Rails.application.routes.url_helpers.rails_blob_path(attachment, only_path: true)
  end
end

app/helpers/apps_helper.rb
module AppsHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/apps/mdx.html.erb
<% content_for :head do %>
  <meta name="apple-itunes-app" content="app-id=547436543">
<% end %>

<p>
Goofy test of app banner for MDX.
</p>
<p>
<a href="https://itunes.apple.com/us/app/my-disney-experience/id547436543?mt=8" style="display:inline-block;overflow:hidden;background:url(https://linkmaker.itunes.apple.com/en-us/badge-lrg.svg?releaseDate=2012-08-02&kind=iossoftware&bubble=ios_apps) no-repeat;width:135px;height:40px;"></a>
</p>

app/views/apps/rename_finder_items_action.html.erb
<% content_for :title, 'Rename Finder Items Action - Samuel Ford' %>

<h2>Rename Finder Items Action</h2>

<p>
  Automator is superb for throwing together simple workflows for things you do all the time or for repetitive 
  actions on groups of files, photos, movies, etc and it has a pretty good set of built in actions. The only 
  built in file rename action, _Rename Finder Items_, can do simple replacements or date/time and sequential 
  renaming but if you need to do something more complex, you're out of luck.
</p>

<%= image_tag 'rename-screenshot.png', class: 'img-responsive center-block' %>

<p>
  <em>Rename Finder Items by Pattern</em> is an Automator action that is similar to the built in <em>Rename 
  Finder Items</em> action that can handle pattern matches with wildcards like this:

  <ul>
    <li>Input File: <code>Screen shot 2015-02-13 at 7.35.03 PM</code></li>
    <li>Search For: <code>Screen shot * at * *M</code></li>
    <li>Replace With: <code>$1-$2-$3M</code></li>
    <li>Output File: <code>2015-02-13-7.35.03-PM</code></li>
  </ul>
</p>

<p>
  You can use as many wildcards as you like in the search pattern. You can use any of them as many times as you 
  like in the replacement pattern by number preceded by a "$". If no match is found for a wildcard, it is 
  substituted with a blank in the replacement pattern.
</p>

<p>
  It's available for free for anyone to use or modify.
</p>

<p>
  Go grab the source or the 0.1 build packaged in a DMG from 
  <a href="https://github.com/samuelwford/rename-finder-items-by-pattern">GitHub</a> and give it a whirl.
</p>

<h4>Notes</h4>

<p>
  Originally, I intended to create an action that used regular expressions for search and replace, but ran 
  into difficulties getting Xcode to generate a bundle with an embedded framework 
  (<a href="http://regexkit.sourceforge.net/">RegexKit</a> in this case) that would load properly when Automator 
  loaded the action bundle. Hopefully, I'll figure out how and the next version will be much more powerful.
</p>

app/views/apps/snippose.html.erb
<% content_for :title, 'Snipposé App - Samuel Ford' %>

<h2>
  Snipposé
  <%= link_to(image_tag('mas.png', class: 'img-responsive pull-right'), 'https://itunes.apple.com/us/app/snippose/id1140313689?ls=1&mt=12') %>
</h2>
  
<p>
A simple macOS tool for briefly hightlighting a small portion of a screen, zooming and centering it on the screen until dismissed. Great for presentations or just quickly checking the pixels on a design.
</p>

<p>
Inspired by a similar tool shown on a WWDC 2016 video.
</p>

<%= image_tag 'snippose-demo.gif', class: 'img-responsive center-block' %>

app/views/images/_form.html.erb
<%= bootstrap_form_for @image do |f| %>
  <%= f.text_field :name, autofocus: true %>
  <%= f.text_field :key %>
  <%= f.file_field :picture %>
  <%= f.form_group do %>
    <%= f.submit %>
  <% end %>
<% end %>

app/views/images/edit.html.erb
<% content_for :title, "#{@image.name} - Image - Samuel Ford" %>

<%= render 'form' %>

app/views/images/index.html.erb
<% content_for :title, 'Images - Samuel Ford' %>

<ul class="list-group">
<% @images.each do |image| %>
  <li class="list-group-item">
    <% if image.picture.attached? %>
      <%= image_tag image.picture.variant(resize: "100x100") %>
      <%= link_to image.name, image.picture %>
    <% else %>
      <%= image.name %>
    <% end %>
    <%= link_to 'Edit', edit_image_path(image), class: 'btn btn-default btn-sm pull-right' %>
  </li>
<% end %>
</ul>

<%= link_to 'New Image', new_image_path, class: 'btn btn-default' %>

app/views/images/new.html.erb
<% content_for :title, 'New Image - Samuel Ford' %>

<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= yield(:head) %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="alternate" type="application/rss+xml" title="Samuel Ford RSS Feed" href="http://www.samuelwford.com/feed?format=rss">
</head>
<body>

<header class="intro-header">
  <div class="container">
    <div class="row">
      <div class="site-heading">
        <h1 class="pull-right">
			  <%= link_to root_path  do %>
			  	<span style="color: darkred">samuel</span><span style="color: darkgreen">w</span><span style="color: darkorange">ford</span>
			  <% end %>
		  </h1>
      </div>
    </div>
  </div>
</header>

<div class="content">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
        <%= link_to 'Home', root_path %> - 
        <%= link_to 'Archive', archive_path %> -
        <%= link_to 'Snipposé', snippose_path %> -
        <%= link_to 'Rename Finder Items', rename_finder_items_action_path %>

        <% if in_the_backdoor? %>
          - <%= link_to 'Unpublished', unpublished_path %>
          - <%= link_to 'Images', images_path %>
        <% end %>

        <%= yield %>
      </div>
    </div>
  </div>
</div>

<div class="footer">
  <div class="container">
    <div class="row">
      <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1 text-center">
        <div class="hr">
          <hr/>
          <img src="http://www.gravatar.com/avatar/0f4db175e1620c9cd713cc1096d41bcf?d=40">
        </div>
        <a href="https://twitter.com/samuelwford/">@samuelwford</a>
      </div>
    </div>
  </div>
</div>

<%= render "shared/footer" %>

</body>
</html>

app/views/posts/_form.html.erb
<%= bootstrap_form_for @post do |f| %>
  <%= f.text_field :title, autofocus: true %>
  <%= f.text_field :slug %>
  <%= f.check_box :published %>
  <%= f.datetime_local_field :posted_at %>
  <%= f.text_field :key %>
  <%= f.text_area :body, rows: '15' %>
  <%= f.form_group do %>
    <%= f.submit %>
  <% end %>
<% end %>

app/views/posts/_post.html.erb
<div class="post">
  <div class="post-header">
    <h2><%= post.title %></h2>
    <div class="post-date"><%= link_to post.posted_at.strftime('%B %e, %Y'), post_path(post.slug_or_id) %></div>
  </div>
  <div class="post-body">
    <%= markdown post.body %>
  </div>
</div>

app/views/posts/archive.html.erb
<% content_for :title, 'Archive - Samuel Ford'%>

<h3>Archive</h3>

<p>
  <ul>
    <% @posts.each do |post| %>
      <li>
        <%= link_to post.posted_at_formatted, post_path(post.slug_or_id) %>
        <%= post.title %>
      </li>
    <% end %>
  </ul>
</p>

app/views/posts/edit.html.erb
<% content_for :title, 'Edit Post - Samuel Ford' %>
<%= render 'form' %>

app/views/posts/index.html.erb
<% content_for :title, 'Samuel Ford' %>

<%= render @posts %>

app/views/posts/new.html.erb
<% content_for :title, 'New Post - Samuel Ford' %>

<%= render 'form' %>

app/views/posts/show.html.erb
<% content_for :title, "#{@post.title} - Samuel Ford" %>

<% content_for :head do %>
  <meta property="og:title" content="<%= @post.title %>">
  <meta property="og:description" content="<%= plaintext @post.teaser %>">
  <meta property="og:site_name" content="Samuel Ford's Blog">
  <meta property="og:url" content="<%= post_path(@post.slug_or_id) %>">
  <meta property="og:type" content="blog">
<% end %>

<%= render @post %>

<%= link_to 'Home', root_path %>

app/views/posts/unpublished.html.erb
<% content_for :title, 'Unpublished - Samuel Ford' %>
<h3>Unpublished</h3>

<p>
  <ul>
    <% @posts.each do |post| %>
      <li>
        <%= link_to post.posted_at_formatted, edit_post_path(post) %>
        <%= post.title %>
      </li>
    <% end %>
  </ul>
</p>

<%= link_to 'New Post', new_post_path, class: 'btn btn-default' %>

<h4>Published</h4>

<p>
  <ul>
    <% @published_posts.each do |post| %>
      <li>
        <%= link_to post.posted_at_formatted, edit_post_path(post) %>
        <%= post.title %>
      </li>
    <% end %>
  </ul>
</p>